name: Dev-Docker-Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Run on ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Declare variables
        run: |
          # add env variable called branch name with the branch name as value ("/" is replaced by "-" in the branch name)
          echo "branch_name="${GITHUB_REF#refs/*/} | sed 's/\//-/g'"" >> $GITHUB_ENV
          # add env variable called sha_short with the shorten commit hash as value
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push image to Amazon ECR
        id: build-image-without-release-version
        run: |
          # build docker image
          npm run docker-build
          # tag docker image so that the workflow knows where to push the image to
          # branch name and commit hash are appended for easy identification
          docker tag dummy-node:latest ${{secrets.ECR_REPO_URI}}:${{env.branch_name}}-${{env.sha_short}}
          docker push ${{secrets.ECR_REPO_URI}}:${{env.branch_name}}-${{env.sha_short}}
          echo "image=${{secrets.ECR_REPO_URI}}:${{env.branch_name}}-${{env.sha_short}}" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition docker-fargate-task-def --query taskDefinition > task-definition.json
          
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image-without-release-version.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
